fieldLayouts:
  0bba0059-87a7-49d6-8e34-29da73185ae9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c7a020a3-c321-4b9b-95ad-0cb06c883413
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 66b2de03-b9c2-4921-b712-b1f055b89d84 # Nft Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc10f89c-d96e-479e-85f9-98c367b982f2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02d47f4e-e0c2-4e11-919b-e28fbec6c6cd # Id nft
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 599df65f-4eb9-4339-86b6-ea6bfe41c9b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2ef9a91c-9a2a-4294-ba86-f07fbeaeb948 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b01a0a45-63df-44f0-96c2-1aedcc1525f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f711dd2-95ae-4aea-ae80-192cdd36586a # Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3525e884-9f4c-486f-91a7-dd0103f00600
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d80e8b5c-68c7-4457-a2c2-3e0129571223 # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64891482-e5c9-4296-91b3-f8a6b460457f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 017b7839-3240-4850-91b5-6ccf0b24b62c # created_at
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 016a387f-4c89-4640-911c-80d3b5987a2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c883bb3-613b-4fe9-afdb-29b1c42267aa # User info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72a1608f-2bee-4ff4-b2aa-226378c6e5fd
            userCondition: null
            warning: null
            width: 100
        name: Nft
        uid: d38d89be-ea25-46aa-8b82-d776ff25bfdb
        userCondition: null
handle: nft
hasTitleField: true
name: Nft
section: 72910ad4-fa3a-48af-bdc5-e10bd89c85af # nft
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
