fieldLayouts:
  4e616811-9a89-4a9d-94db-e7b8877fcf6a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 54de9ce9-93e4-44b7-9d55-80123d636854
            userCondition: null
            warning: null
            width: 100
        name: Contenu
        uid: 5c8d90f0-9af5-412f-88ef-db01d93340f9
        userCondition: null
fs: nft
handle: nft
name: Nft
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
