columnSuffix: fsagtzih
contentColumnType: 'decimal(15,5)'
fieldGroup: cef4e03d-69e6-4316-906a-24b1252e9b66 # Nft
handle: price
instructions: 'Eth Price of your nft'
name: Price
searchable: false
settings:
  decimals: 5
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
