defaultPlacement: end
enableVersioning: true
handle: nft
name: nft
propagationMethod: all
siteSettings:
  083ec8b5-3a63-4e14-a498-44f7083bed08: # nft_card
    enabledByDefault: true
    hasUrls: true
    template: nft/_entry
    uriFormat: 'nft/{slug}'
type: channel
